inc:
  # Blog Information
  title:        "Vict0rsch"
  subtitle:     "(Deep) Learning Enthusiast"
  cover_image:  blog-cover.jpg
  logo:         light-bulb.svg
  description: "Vict0rsch's blog about tech and AI - PhD Student @MILA, Montréal, Québec"
  
  # Company information
  company:      
  url:          
  facebook:     
  twitter:      vict0rsch
  gplus:
  github:       https://github.com/vict0rsch/deep_learning
  linkedin:     https://fr.linkedin.com/in/victor-schmidt-30418083
  mail:         vsch@pm.me   
  
  # Product Information
  resources_link: /resources
  about_link: /about
  search_link: /search
  tagline:      "Learn Keras and Lasagne (2015)"
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  http-vict0rsch-github-io
  
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      false
    hn:         false
    
  
 # Analytics     
  analytics:
    google: UA-88678459-1 # Add tracking code in _includes/_google-analytics.html
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font_headers: 'Montserrat:400,700'
  google_font_body: 'Nunito:400,700'
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss
  tutorials_link: /tutorials

url:         https://vict0rs.ch
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    UTC+1
plugins: [jekyll-paginate]

# Show future posts
future:      true
show_drafts: nil
limit_posts: 500
highlighter: rouge

relative_permalinks: false

permalink:     pretty
paginate_path: 'posts/:num'
paginate: 5

markdown:      kramdown
markdown_ext:  kramdown, markdown,mkd,mkdn,md
textile_ext:   textile
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM

syntax_highlighter_opts:
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
# bundle exec jekyll serve
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false